const List<String> kDoctorSpecialties = [
  'Allergist / Immunologist',
  'Cardiologist',
  'Dentist / Periodontist',
  'Dermatologist',
  'Endocrinologist',
  'Gastroenterologist / Hepatologist / Proctologist',
  'Gynecologist / Obstetrician (OB/GYN)',
  'Hematologist',
  'Nephrologist',
  'Neurologist',
  'Ophthalmologist',
  'Orthopedic Surgeon / Rheumatologist',
  'Otolaryngologist (ENT)',
  'Pediatrician',
  'Psychiatrist',
  'Pulmonologist / Sleep Specialist',
  'Urologist',
  'General Surgery / Critical Care / Pain Management',
];
